### ISSUE TITLE
Retroarch Structure Error

### ISSUE THREAD

**Issue by qzizzleferreal** [thebezelproject/BezelProject-Windows#24] opened 2021-02-13 20:33 UTC
Hi - I'm having issues (RetroArch Structure Error) when I select preferences and attempt to point to the RetroArch install directory. I keep getting an error that indicates the retroarch.cfg file cannot be found. My retroarch directory is simply C:\RetroArch. 
<img width="302" alt="Screenshot 2021-02-13 143051" src="https://user-images.githubusercontent.com/43578432/107860976-64828080-6e08-11eb-830c-e44422accbf2.png">

**Comment by thebezelproject** [comment] 2021-02-14 00:58
The error shows that the Preferences value for the Retroarch install directory is C:\RetroArchC, not C:\Retroarch. Which is correct? Also, does the config directory under Retroarch exist? Could it be an owership/permissions issue?

**Comment by qzizzleferreal** [comment] 2021-02-14 15:19
It's definitely just C:\Retroarch. I even tried adding a C at the end and the error then showed "C:\RetroArchCC". I have no idea where the extra C is coming from. Here is a screenshot of my directory:
<img width="664" alt="Screenshot 2021-02-14 091915" src="https://user-images.githubusercontent.com/43578432/107880643-c0e7ad80-6ea5-11eb-8fdf-9e99bcc0583f.png">

**Comment by thebezelproject** [comment] 2021-02-14 16:31
Please edit the bezel project.ini file from the installation and see what value is stored for the retroarch value and report it here.

**Comment by qzizzleferreal** [comment] 2021-02-14 16:43
<img width="717" alt="Screenshot 2021-02-14 104244" src="https://user-images.githubusercontent.com/43578432/107882897-779d5b00-6eb1-11eb-834f-240b2ac4aa34.png">

**Comment by thebezelproject** [comment] 2021-02-14 17:10
I am currently at a loss. I have duplicated your install here and do not receive any errors. All I can come up with is some kind of ownership/permissions issue that the app isn't coded to deal with.

What OS and version are you running? As a test, could you create a test directory (maybe C:\Emulators), install Retroarch into that, then reconfigure the app to point to the test directory? Report results here.

**Comment by qzizzleferreal** [comment] 2021-02-14 21:46
I think I found the issue - for some reason in my retroarch.cfg file, the rgui_config line was pointing to that weird RetroarchC file that didn't exist. Must have been something I screwed up a long time ago. Adjusted that back to the default and the installer has started working. Thanks!

**Comment by SireSalty** [comment] 2024-01-07 22:47
I'm having this issue as well with an emudeck windows install.  Including from a fresh windows installation

**Comment by thebezelproject** [comment] 2024-01-08 00:53
While an EMUDECK installation isn't supported, the Windows Bezel Project installer should work as long as the preferences are correct.

Having said that, I will be happy to work with you if you can provide more information. Look over the info above and provide all the relative information from your installation of EmuDeck so we can debug what is going wrong.

**Comment by SireSalty** [comment] 2024-01-08 01:42
I appreciate the assist, wasn't sure if you would be able to help since the windows project seems to be at a stable state.

So the variables in question were not listed within the CFG, so it should default to the directory of the retroarch cfg file.   I HAD it working somehow for a few systems and then the installer broke as I installed new systems, so I couldn't get it to work again.   I reimaged the system from a pre-installation image (I only had steam and emudeck installed for big picture).

I appreciate all the help!  I can bring the image back to pre-retroarch/bezel install at a moments notice.

![image](https://github.com/thebezelproject/BezelProject-Windows/assets/85232911/7bd78bb3-fd65-494f-8b30-d767db89dda0)
![image](https://github.com/thebezelproject/BezelProject-Windows/assets/85232911/e3d31284-588a-47c0-a91c-1a2f13183243)
![image](https://github.com/thebezelproject/BezelProject-Windows/assets/85232911/5dd7df33-50c1-4e41-a105-348631a16c5d)
![image](https://github.com/thebezelproject/BezelProject-Windows/assets/85232911/8285cf82-4912-48d5-b434-ad19f4a1fa7f)
![image](https://github.com/thebezelproject/BezelProject-Windows/assets/85232911/fa39f781-af9b-4b88-a058-901978dadfea)

**Comment by thebezelproject** [comment] 2024-01-08 02:14
I see nothing wrong from your pics (thanks for those). I will have to create a test system and install EmuDeck for Windows and debug from there. I'll get back here when I know more.

**Comment by SireSalty** [comment] 2024-01-08 03:14
Thank you.  Let me know any way I can help with repo testing

**Comment by thebezelproject** [comment] 2024-01-09 02:02
I have discovered the issue, but I will say this before proceeding. EmuDeck isn't setup for The Bezel Project in that it uses a custom Retroarch.cfg file (this is the root cause of the app error message and is warned about in the initial Help screen), and custom settings for the default bezels located in the overlays\pegasus directory which would affect bezels from our project. All in all, to undo everything would require a ton of manual editing which would be lost if you used the EmuDeck option to update Retroarch.

I recommend just using the portable Emulation Station Desktop Edition for Windows. Let me know if you want any more details.

**Comment by SireSalty** [comment] 2024-01-11 19:01
I didn't install pegasus, even when it did work.  So not sure.  I was trying to use this with big picture, which doesn't really work well with straight portable retroarch.  I appreciate the help on this and trying to look into it.

**Comment by thebezelproject** [comment] 2024-01-11 19:12
From what I can see, the code for installation of EmuDeck's emulators has of course been changed and updated over time. It is always possible the EmuDeck team will implement native support of the Bezel Project. Other similar efforts have done so. I'll keep an eye out. I'll close this for now.

**Closed as completed by thebezelproject** 2024-01-11 19:12 UTC
